# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1434c8dbf86f9c0422aab556795bb6127f32e4e6a6b8ce7513d338f9074fab7a0ba6caf22ca6041342433b8bd56c5c20a697197b3775b20e9d257b9295222277

test:
  secret_key_base: 3102eac92250265d5d4360e0893952a891e9372ff49a9e6e2219f631ee9ab1c4d7a1cded7410259e58cb0e3d3c148caaa86959e83c9f43d4513b579fba8bf664

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
